import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton, SignInButton, SignOutButton, auth } from "@clerk/nextjs";
import Header from "@/components/Header";
import { sql } from "@vercel/postgres";
import CreateProfile from "@/components/CreateProfile";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  const { userId } = auth();
  
  // go and get the user profile from our db
  const profileRes = await sql`SELECT * FROM sn_profiles WHERE clerk_user_id = ${userId}`;

  console.log({userId},' -User id');
  //console.log(profileRes.clerk_user_id);
  //console.log(profileRes.rowCount);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
         

          <h1>Social Profile</h1>

          <SignInButton />
           {profileRes.rowCount !== 0 && children}

          {profileRes.rowCount === 0 && <CreateProfile />}
        </body>
      </html>
    </ClerkProvider>
  );
}
